# sample command - kubectl create cm demo --from-literal=db=postgress:1234 --dry-run=client -o yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo1
data:
  db: vertica-nginx
  user: sachin-nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
  labels:
    app: test-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-nginx
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          env:
            - name: DB
              valueFrom:
                configMapKeyRef:
                  name: demo1
                  key: db
            - name: User
              valueFrom:
                configMapKeyRef:
                  name: demo1
                  key: user
