apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
data:
  dbname: "prod-db"
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-vol
  labels:
    app: test-nginx-vol
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-nginx-vol
  template:
    metadata:
      labels:
        app: test-nginx-vol
    spec:
      containers:
        - name: app
          image: nginx
          volumeMounts:
            - name: config-volume
              mountPath: "/etc/config"   # folder where files will appear
      volumes:
        - name: config-volume
          configMap:
            name: myconfig
