apiVersion: v1
kind: Secret
metadata:
  name: secret1
data:
  db: dmVydGljYS1zZWNyZXQ=  # base64 of "vertica-secret"
  user: c2FjaGluLXNlY3JldA==  # base64 of "sachin-secret"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-sec
  labels:
    app: test-nginx-sec
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-nginx-sec
  template:
    metadata:
      labels:
        app: test-nginx-sec
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          env:
            - name: DBsec
              valueFrom:
                secretKeyRef:
                  name: secret1
                  key: db
            - name: Usersec
              valueFrom:
                secretKeyRef:
                  name: secret1
                  key: user
